default_stages: [pre-commit]
default_language_version:
    python: python3.12
repos:
-   repo: local
    hooks:
    -   id: format
        name: format
        entry: uv run ruff format
        language: system
        files: .*\.(py|ipynb)$
    -   id: lint
        name: lint
        entry: uv run ruff check
        language: system
        files: .*\.(py|ipynb)$
    -   id: type-check
        name: type-check
        entry: uv run mypy exparso --explicit-package-bases
        language: system
        pass_filenames: false
    -   id: unittest
        name: unittest
        language: system
        always_run: true
        pass_filenames: false
        entry: uv run pytest tests/unit
