default_stages: [pre-commit]
default_language_version:
    python: python3.12
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: uv run black --diff --check
        language: system
        files: .*\.(py|ipynb)$
    -   id: isort
        name: isort
        entry: uv run isort --check-only
        language: system
        files: .*\.(py|ipynb)$
    -   id: flake8
        name: flake8
        entry: uv run flake8 --count --show-source --statistics
        language: system        
        files: .*\.(py|ipynb)$
    -   id: unittest
        name: unittest
        language: system
        always_run: true
        pass_filenames: false
        entry: uv run pytest tests/unit
