PDF_TABLE_DOCUMENT = "tests/data/test.pdf"
MARKDOWN_TEXT_DOCUMENT = "tests/data/test.md"
JPEG_DOCUMENT = "tests/data/test.jpg"
BMP_DOCUMENT = "tests/data/test.bmp"
CSV_DOCUMENT = "tests/data/test.csv"
XLSX_DOCUMENT = "tests/data/test.xlsx"
PPTX_DOCUMENT = "tests/data/test.pptx"
DOCX_DOCUMENT = "tests/data/test.docx"
