name: lint

on:
  workflow_call:

env:
  SRC_DIR: .
  PYTHON_VERSION: 3.12  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.20"

      - name: Run black
        run: uv run --only-group dev black $SRC_DIR --diff --check

      - name: Run isort
        run: uv run --only-group dev isort $SRC_DIR --check-only

      - name: Run flake8
        run: uv run --only-group dev flake8 $SRC_DIR --count --show-source --statistics
