name: lint

on:
  workflow_call:

env:
  SRC_DIR: .
  PYTHON_VERSION: 3.12

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.20"

      - name: Run lint
        run: uv run --only-group dev ruff check $SRC_DIR

      - name: Run format check
        run: uv run --only-group dev ruff format --check $SRC_DIR
